---
title: Assignment 2
lab: https://github.com/rhildred/INFO8985-observable-microfrontend
---
## Agenda

- Unfortunately, I couldn't make the microfrontend work
- I decided to make [Assignment 2](`r rmarkdown::metadata$lab`) a case study
- There is a deployment diagram in the final exam so the deliverable is an explained deployment diagram in a word document.
- I will describe the case in the github above and provide a starter deployment diagram.
- Class today is to work the case.

## Final Exam

- the final exam is in the same format as the midterm
- 4 questions each worth 5 points
- 1 question asks for a deployment diagram 
- please remember that there is no 1 correct answer for many development or operational situations
- support your answers with the things you learned from wrestling with otel this term

## Draw your thinking to these outcomes:

- Measure the REDS or Google golden metrics to provide feedback for operational success.
- Select and implement tools to log from micro-front end UI to micro-services to meet operational requirements
- Support daily reports for management overview of throughput for operational success
- Recommend white box or black box techniques as indicated by information needs of business and stakeholder requirements. (this one has the deployment diagram)
